name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: install nightly rust
      run: rustup install nightly; rustup +nightly component add rustfmt clippy
      
    # cargo fmt
    - uses: actions/checkout@v3
    - name: fmt
      run: cargo +nightly fmt --all --check

    # run cargo clippy
    - name: Clippy
      run: cargo +nightly clippy --all-targets

  cross-testing:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          toolchain: ${{ matrix.rust }}

      - run: cargo build --verbose
      - run: cargo test --verbose
